// Copyright 2015 Adam Grandquist

#import <Cocoa/Cocoa.h>
#import <XCTest/XCTest.h>
#import <libReQL.h>

@interface ObjcTestBasicTimeArithmetic487 : XCTestCase

@end

@implementation ObjcTestBasicTimeArithmetic487


- (void)test10 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSNumber *var0 = [NSNumber numberWithBool:YES];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test11 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSNumber *var0 = @1;
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test12 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSNumber *var0 = @1000000000;
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test13 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSNumber *var0 = [NSNumber numberWithBool:YES];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test14 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSNumber *var0 = @-1;
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test15 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSNumber *var0 = @-1000000000;
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test16 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:4];
  NSMutableDictionary *var1 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var2 = @"func";
  NSString *var3 = @"rt1";
  [var1 setObject:var3 forKey:var2];
  [var0 addObject:var1];
  NSMutableDictionary *var4 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var5 = @"func";
  NSString *var6 = @"rt2";
  [var4 setObject:var6 forKey:var5];
  [var0 addObject:var4];
  NSMutableDictionary *var7 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var8 = @"func";
  NSString *var9 = @"rt3";
  [var7 setObject:var9 forKey:var8];
  [var0 addObject:var7];
  NSMutableDictionary *var10 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var11 = @"func";
  NSString *var12 = @"rt4";
  [var10 setObject:var12 forKey:var11];
  [var0 addObject:var10];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test17 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableDictionary *var0 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var1 = @"func";
  NSString *var2 = @"err";
  [var0 setObject:var2 forKey:var1];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test18 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:4];
  NSMutableDictionary *var1 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var2 = @"func";
  NSString *var3 = @"rt1";
  [var1 setObject:var3 forKey:var2];
  [var0 addObject:var1];
  NSMutableDictionary *var4 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var5 = @"func";
  NSString *var6 = @"rt2";
  [var4 setObject:var6 forKey:var5];
  [var0 addObject:var4];
  NSMutableDictionary *var7 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var8 = @"func";
  NSString *var9 = @"rt3";
  [var7 setObject:var9 forKey:var8];
  [var0 addObject:var7];
  NSMutableDictionary *var10 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var11 = @"func";
  NSString *var12 = @"rt4";
  [var10 setObject:var12 forKey:var11];
  [var0 addObject:var10];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test19 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var1 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var2 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var3 = [NSNumber numberWithBool:NO];
  [var2 addObject:var3];
  NSNumber *var4 = [NSNumber numberWithBool:YES];
  [var2 addObject:var4];
  NSNumber *var5 = [NSNumber numberWithBool:YES];
  [var2 addObject:var5];
  NSNumber *var6 = [NSNumber numberWithBool:NO];
  [var2 addObject:var6];
  NSNumber *var7 = [NSNumber numberWithBool:YES];
  [var2 addObject:var7];
  NSNumber *var8 = [NSNumber numberWithBool:NO];
  [var2 addObject:var8];
  [var1 addObject:var2];
  NSMutableArray *var9 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var10 = [NSNumber numberWithBool:YES];
  [var9 addObject:var10];
  NSNumber *var11 = [NSNumber numberWithBool:YES];
  [var9 addObject:var11];
  NSNumber *var12 = [NSNumber numberWithBool:NO];
  [var9 addObject:var12];
  NSNumber *var13 = [NSNumber numberWithBool:YES];
  [var9 addObject:var13];
  NSNumber *var14 = [NSNumber numberWithBool:NO];
  [var9 addObject:var14];
  NSNumber *var15 = [NSNumber numberWithBool:NO];
  [var9 addObject:var15];
  [var1 addObject:var9];
  NSMutableArray *var16 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var17 = [NSNumber numberWithBool:YES];
  [var16 addObject:var17];
  NSNumber *var18 = [NSNumber numberWithBool:YES];
  [var16 addObject:var18];
  NSNumber *var19 = [NSNumber numberWithBool:NO];
  [var16 addObject:var19];
  NSNumber *var20 = [NSNumber numberWithBool:YES];
  [var16 addObject:var20];
  NSNumber *var21 = [NSNumber numberWithBool:NO];
  [var16 addObject:var21];
  NSNumber *var22 = [NSNumber numberWithBool:NO];
  [var16 addObject:var22];
  [var1 addObject:var16];
  NSMutableArray *var23 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var24 = [NSNumber numberWithBool:YES];
  [var23 addObject:var24];
  NSNumber *var25 = [NSNumber numberWithBool:YES];
  [var23 addObject:var25];
  NSNumber *var26 = [NSNumber numberWithBool:NO];
  [var23 addObject:var26];
  NSNumber *var27 = [NSNumber numberWithBool:YES];
  [var23 addObject:var27];
  NSNumber *var28 = [NSNumber numberWithBool:NO];
  [var23 addObject:var28];
  NSNumber *var29 = [NSNumber numberWithBool:NO];
  [var23 addObject:var29];
  [var1 addObject:var23];
  [var0 addObject:var1];
  NSMutableArray *var30 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var31 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var32 = [NSNumber numberWithBool:NO];
  [var31 addObject:var32];
  NSNumber *var33 = [NSNumber numberWithBool:NO];
  [var31 addObject:var33];
  NSNumber *var34 = [NSNumber numberWithBool:NO];
  [var31 addObject:var34];
  NSNumber *var35 = [NSNumber numberWithBool:YES];
  [var31 addObject:var35];
  NSNumber *var36 = [NSNumber numberWithBool:YES];
  [var31 addObject:var36];
  NSNumber *var37 = [NSNumber numberWithBool:YES];
  [var31 addObject:var37];
  [var30 addObject:var31];
  NSMutableArray *var38 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var39 = [NSNumber numberWithBool:NO];
  [var38 addObject:var39];
  NSNumber *var40 = [NSNumber numberWithBool:YES];
  [var38 addObject:var40];
  NSNumber *var41 = [NSNumber numberWithBool:YES];
  [var38 addObject:var41];
  NSNumber *var42 = [NSNumber numberWithBool:NO];
  [var38 addObject:var42];
  NSNumber *var43 = [NSNumber numberWithBool:YES];
  [var38 addObject:var43];
  NSNumber *var44 = [NSNumber numberWithBool:NO];
  [var38 addObject:var44];
  [var30 addObject:var38];
  NSMutableArray *var45 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var46 = [NSNumber numberWithBool:YES];
  [var45 addObject:var46];
  NSNumber *var47 = [NSNumber numberWithBool:YES];
  [var45 addObject:var47];
  NSNumber *var48 = [NSNumber numberWithBool:NO];
  [var45 addObject:var48];
  NSNumber *var49 = [NSNumber numberWithBool:YES];
  [var45 addObject:var49];
  NSNumber *var50 = [NSNumber numberWithBool:NO];
  [var45 addObject:var50];
  NSNumber *var51 = [NSNumber numberWithBool:NO];
  [var45 addObject:var51];
  [var30 addObject:var45];
  NSMutableArray *var52 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var53 = [NSNumber numberWithBool:YES];
  [var52 addObject:var53];
  NSNumber *var54 = [NSNumber numberWithBool:YES];
  [var52 addObject:var54];
  NSNumber *var55 = [NSNumber numberWithBool:NO];
  [var52 addObject:var55];
  NSNumber *var56 = [NSNumber numberWithBool:YES];
  [var52 addObject:var56];
  NSNumber *var57 = [NSNumber numberWithBool:NO];
  [var52 addObject:var57];
  NSNumber *var58 = [NSNumber numberWithBool:NO];
  [var52 addObject:var58];
  [var30 addObject:var52];
  [var0 addObject:var30];
  NSMutableArray *var59 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var60 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var61 = [NSNumber numberWithBool:NO];
  [var60 addObject:var61];
  NSNumber *var62 = [NSNumber numberWithBool:NO];
  [var60 addObject:var62];
  NSNumber *var63 = [NSNumber numberWithBool:NO];
  [var60 addObject:var63];
  NSNumber *var64 = [NSNumber numberWithBool:YES];
  [var60 addObject:var64];
  NSNumber *var65 = [NSNumber numberWithBool:YES];
  [var60 addObject:var65];
  NSNumber *var66 = [NSNumber numberWithBool:YES];
  [var60 addObject:var66];
  [var59 addObject:var60];
  NSMutableArray *var67 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var68 = [NSNumber numberWithBool:NO];
  [var67 addObject:var68];
  NSNumber *var69 = [NSNumber numberWithBool:NO];
  [var67 addObject:var69];
  NSNumber *var70 = [NSNumber numberWithBool:NO];
  [var67 addObject:var70];
  NSNumber *var71 = [NSNumber numberWithBool:YES];
  [var67 addObject:var71];
  NSNumber *var72 = [NSNumber numberWithBool:YES];
  [var67 addObject:var72];
  NSNumber *var73 = [NSNumber numberWithBool:YES];
  [var67 addObject:var73];
  [var59 addObject:var67];
  NSMutableArray *var74 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var75 = [NSNumber numberWithBool:NO];
  [var74 addObject:var75];
  NSNumber *var76 = [NSNumber numberWithBool:YES];
  [var74 addObject:var76];
  NSNumber *var77 = [NSNumber numberWithBool:YES];
  [var74 addObject:var77];
  NSNumber *var78 = [NSNumber numberWithBool:NO];
  [var74 addObject:var78];
  NSNumber *var79 = [NSNumber numberWithBool:YES];
  [var74 addObject:var79];
  NSNumber *var80 = [NSNumber numberWithBool:NO];
  [var74 addObject:var80];
  [var59 addObject:var74];
  NSMutableArray *var81 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var82 = [NSNumber numberWithBool:YES];
  [var81 addObject:var82];
  NSNumber *var83 = [NSNumber numberWithBool:YES];
  [var81 addObject:var83];
  NSNumber *var84 = [NSNumber numberWithBool:NO];
  [var81 addObject:var84];
  NSNumber *var85 = [NSNumber numberWithBool:YES];
  [var81 addObject:var85];
  NSNumber *var86 = [NSNumber numberWithBool:NO];
  [var81 addObject:var86];
  NSNumber *var87 = [NSNumber numberWithBool:NO];
  [var81 addObject:var87];
  [var59 addObject:var81];
  [var0 addObject:var59];
  NSMutableArray *var88 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var89 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var90 = [NSNumber numberWithBool:NO];
  [var89 addObject:var90];
  NSNumber *var91 = [NSNumber numberWithBool:NO];
  [var89 addObject:var91];
  NSNumber *var92 = [NSNumber numberWithBool:NO];
  [var89 addObject:var92];
  NSNumber *var93 = [NSNumber numberWithBool:YES];
  [var89 addObject:var93];
  NSNumber *var94 = [NSNumber numberWithBool:YES];
  [var89 addObject:var94];
  NSNumber *var95 = [NSNumber numberWithBool:YES];
  [var89 addObject:var95];
  [var88 addObject:var89];
  NSMutableArray *var96 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var97 = [NSNumber numberWithBool:NO];
  [var96 addObject:var97];
  NSNumber *var98 = [NSNumber numberWithBool:NO];
  [var96 addObject:var98];
  NSNumber *var99 = [NSNumber numberWithBool:NO];
  [var96 addObject:var99];
  NSNumber *var100 = [NSNumber numberWithBool:YES];
  [var96 addObject:var100];
  NSNumber *var101 = [NSNumber numberWithBool:YES];
  [var96 addObject:var101];
  NSNumber *var102 = [NSNumber numberWithBool:YES];
  [var96 addObject:var102];
  [var88 addObject:var96];
  NSMutableArray *var103 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var104 = [NSNumber numberWithBool:NO];
  [var103 addObject:var104];
  NSNumber *var105 = [NSNumber numberWithBool:NO];
  [var103 addObject:var105];
  NSNumber *var106 = [NSNumber numberWithBool:NO];
  [var103 addObject:var106];
  NSNumber *var107 = [NSNumber numberWithBool:YES];
  [var103 addObject:var107];
  NSNumber *var108 = [NSNumber numberWithBool:YES];
  [var103 addObject:var108];
  NSNumber *var109 = [NSNumber numberWithBool:YES];
  [var103 addObject:var109];
  [var88 addObject:var103];
  NSMutableArray *var110 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var111 = [NSNumber numberWithBool:NO];
  [var110 addObject:var111];
  NSNumber *var112 = [NSNumber numberWithBool:YES];
  [var110 addObject:var112];
  NSNumber *var113 = [NSNumber numberWithBool:YES];
  [var110 addObject:var113];
  NSNumber *var114 = [NSNumber numberWithBool:NO];
  [var110 addObject:var114];
  NSNumber *var115 = [NSNumber numberWithBool:YES];
  [var110 addObject:var115];
  NSNumber *var116 = [NSNumber numberWithBool:NO];
  [var110 addObject:var116];
  [var88 addObject:var110];
  [var0 addObject:var88];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test21 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:8];
  NSMutableArray *var1 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var2 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var3 = [NSNumber numberWithBool:YES];
  [var2 addObject:var3];
  NSNumber *var4 = [NSNumber numberWithBool:YES];
  [var2 addObject:var4];
  NSNumber *var5 = [NSNumber numberWithBool:NO];
  [var2 addObject:var5];
  NSNumber *var6 = [NSNumber numberWithBool:YES];
  [var2 addObject:var6];
  NSNumber *var7 = [NSNumber numberWithBool:NO];
  [var2 addObject:var7];
  NSNumber *var8 = [NSNumber numberWithBool:NO];
  [var2 addObject:var8];
  [var1 addObject:var2];
  NSMutableArray *var9 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var10 = [NSNumber numberWithBool:NO];
  [var9 addObject:var10];
  NSNumber *var11 = [NSNumber numberWithBool:NO];
  [var9 addObject:var11];
  NSNumber *var12 = [NSNumber numberWithBool:NO];
  [var9 addObject:var12];
  NSNumber *var13 = [NSNumber numberWithBool:YES];
  [var9 addObject:var13];
  NSNumber *var14 = [NSNumber numberWithBool:YES];
  [var9 addObject:var14];
  NSNumber *var15 = [NSNumber numberWithBool:YES];
  [var9 addObject:var15];
  [var1 addObject:var9];
  [var0 addObject:var1];
  NSMutableArray *var16 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var17 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var18 = [NSNumber numberWithBool:YES];
  [var17 addObject:var18];
  NSNumber *var19 = [NSNumber numberWithBool:YES];
  [var17 addObject:var19];
  NSNumber *var20 = [NSNumber numberWithBool:NO];
  [var17 addObject:var20];
  NSNumber *var21 = [NSNumber numberWithBool:YES];
  [var17 addObject:var21];
  NSNumber *var22 = [NSNumber numberWithBool:NO];
  [var17 addObject:var22];
  NSNumber *var23 = [NSNumber numberWithBool:NO];
  [var17 addObject:var23];
  [var16 addObject:var17];
  NSMutableArray *var24 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var25 = [NSNumber numberWithBool:NO];
  [var24 addObject:var25];
  NSNumber *var26 = [NSNumber numberWithBool:NO];
  [var24 addObject:var26];
  NSNumber *var27 = [NSNumber numberWithBool:NO];
  [var24 addObject:var27];
  NSNumber *var28 = [NSNumber numberWithBool:YES];
  [var24 addObject:var28];
  NSNumber *var29 = [NSNumber numberWithBool:YES];
  [var24 addObject:var29];
  NSNumber *var30 = [NSNumber numberWithBool:YES];
  [var24 addObject:var30];
  [var16 addObject:var24];
  [var0 addObject:var16];
  NSMutableArray *var31 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var32 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var33 = [NSNumber numberWithBool:YES];
  [var32 addObject:var33];
  NSNumber *var34 = [NSNumber numberWithBool:YES];
  [var32 addObject:var34];
  NSNumber *var35 = [NSNumber numberWithBool:NO];
  [var32 addObject:var35];
  NSNumber *var36 = [NSNumber numberWithBool:YES];
  [var32 addObject:var36];
  NSNumber *var37 = [NSNumber numberWithBool:NO];
  [var32 addObject:var37];
  NSNumber *var38 = [NSNumber numberWithBool:NO];
  [var32 addObject:var38];
  [var31 addObject:var32];
  NSMutableArray *var39 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var40 = [NSNumber numberWithBool:NO];
  [var39 addObject:var40];
  NSNumber *var41 = [NSNumber numberWithBool:NO];
  [var39 addObject:var41];
  NSNumber *var42 = [NSNumber numberWithBool:NO];
  [var39 addObject:var42];
  NSNumber *var43 = [NSNumber numberWithBool:YES];
  [var39 addObject:var43];
  NSNumber *var44 = [NSNumber numberWithBool:YES];
  [var39 addObject:var44];
  NSNumber *var45 = [NSNumber numberWithBool:YES];
  [var39 addObject:var45];
  [var31 addObject:var39];
  [var0 addObject:var31];
  NSMutableArray *var46 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var47 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var48 = [NSNumber numberWithBool:YES];
  [var47 addObject:var48];
  NSNumber *var49 = [NSNumber numberWithBool:YES];
  [var47 addObject:var49];
  NSNumber *var50 = [NSNumber numberWithBool:NO];
  [var47 addObject:var50];
  NSNumber *var51 = [NSNumber numberWithBool:YES];
  [var47 addObject:var51];
  NSNumber *var52 = [NSNumber numberWithBool:NO];
  [var47 addObject:var52];
  NSNumber *var53 = [NSNumber numberWithBool:NO];
  [var47 addObject:var53];
  [var46 addObject:var47];
  NSMutableArray *var54 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var55 = [NSNumber numberWithBool:NO];
  [var54 addObject:var55];
  NSNumber *var56 = [NSNumber numberWithBool:NO];
  [var54 addObject:var56];
  NSNumber *var57 = [NSNumber numberWithBool:NO];
  [var54 addObject:var57];
  NSNumber *var58 = [NSNumber numberWithBool:YES];
  [var54 addObject:var58];
  NSNumber *var59 = [NSNumber numberWithBool:YES];
  [var54 addObject:var59];
  NSNumber *var60 = [NSNumber numberWithBool:YES];
  [var54 addObject:var60];
  [var46 addObject:var54];
  [var0 addObject:var46];
  NSMutableArray *var61 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var62 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var63 = [NSNumber numberWithBool:NO];
  [var62 addObject:var63];
  NSNumber *var64 = [NSNumber numberWithBool:NO];
  [var62 addObject:var64];
  NSNumber *var65 = [NSNumber numberWithBool:NO];
  [var62 addObject:var65];
  NSNumber *var66 = [NSNumber numberWithBool:YES];
  [var62 addObject:var66];
  NSNumber *var67 = [NSNumber numberWithBool:YES];
  [var62 addObject:var67];
  NSNumber *var68 = [NSNumber numberWithBool:YES];
  [var62 addObject:var68];
  [var61 addObject:var62];
  NSMutableArray *var69 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var70 = [NSNumber numberWithBool:YES];
  [var69 addObject:var70];
  NSNumber *var71 = [NSNumber numberWithBool:YES];
  [var69 addObject:var71];
  NSNumber *var72 = [NSNumber numberWithBool:NO];
  [var69 addObject:var72];
  NSNumber *var73 = [NSNumber numberWithBool:YES];
  [var69 addObject:var73];
  NSNumber *var74 = [NSNumber numberWithBool:NO];
  [var69 addObject:var74];
  NSNumber *var75 = [NSNumber numberWithBool:NO];
  [var69 addObject:var75];
  [var61 addObject:var69];
  [var0 addObject:var61];
  NSMutableArray *var76 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var77 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var78 = [NSNumber numberWithBool:YES];
  [var77 addObject:var78];
  NSNumber *var79 = [NSNumber numberWithBool:YES];
  [var77 addObject:var79];
  NSNumber *var80 = [NSNumber numberWithBool:NO];
  [var77 addObject:var80];
  NSNumber *var81 = [NSNumber numberWithBool:YES];
  [var77 addObject:var81];
  NSNumber *var82 = [NSNumber numberWithBool:NO];
  [var77 addObject:var82];
  NSNumber *var83 = [NSNumber numberWithBool:NO];
  [var77 addObject:var83];
  [var76 addObject:var77];
  NSMutableArray *var84 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var85 = [NSNumber numberWithBool:NO];
  [var84 addObject:var85];
  NSNumber *var86 = [NSNumber numberWithBool:NO];
  [var84 addObject:var86];
  NSNumber *var87 = [NSNumber numberWithBool:NO];
  [var84 addObject:var87];
  NSNumber *var88 = [NSNumber numberWithBool:YES];
  [var84 addObject:var88];
  NSNumber *var89 = [NSNumber numberWithBool:YES];
  [var84 addObject:var89];
  NSNumber *var90 = [NSNumber numberWithBool:YES];
  [var84 addObject:var90];
  [var76 addObject:var84];
  [var0 addObject:var76];
  NSMutableArray *var91 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var92 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var93 = [NSNumber numberWithBool:YES];
  [var92 addObject:var93];
  NSNumber *var94 = [NSNumber numberWithBool:YES];
  [var92 addObject:var94];
  NSNumber *var95 = [NSNumber numberWithBool:NO];
  [var92 addObject:var95];
  NSNumber *var96 = [NSNumber numberWithBool:YES];
  [var92 addObject:var96];
  NSNumber *var97 = [NSNumber numberWithBool:NO];
  [var92 addObject:var97];
  NSNumber *var98 = [NSNumber numberWithBool:NO];
  [var92 addObject:var98];
  [var91 addObject:var92];
  NSMutableArray *var99 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var100 = [NSNumber numberWithBool:NO];
  [var99 addObject:var100];
  NSNumber *var101 = [NSNumber numberWithBool:NO];
  [var99 addObject:var101];
  NSNumber *var102 = [NSNumber numberWithBool:NO];
  [var99 addObject:var102];
  NSNumber *var103 = [NSNumber numberWithBool:YES];
  [var99 addObject:var103];
  NSNumber *var104 = [NSNumber numberWithBool:YES];
  [var99 addObject:var104];
  NSNumber *var105 = [NSNumber numberWithBool:YES];
  [var99 addObject:var105];
  [var91 addObject:var99];
  [var0 addObject:var91];
  NSMutableArray *var106 = [NSMutableArray arrayWithCapacity:2];
  NSMutableArray *var107 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var108 = [NSNumber numberWithBool:YES];
  [var107 addObject:var108];
  NSNumber *var109 = [NSNumber numberWithBool:YES];
  [var107 addObject:var109];
  NSNumber *var110 = [NSNumber numberWithBool:NO];
  [var107 addObject:var110];
  NSNumber *var111 = [NSNumber numberWithBool:YES];
  [var107 addObject:var111];
  NSNumber *var112 = [NSNumber numberWithBool:NO];
  [var107 addObject:var112];
  NSNumber *var113 = [NSNumber numberWithBool:NO];
  [var107 addObject:var113];
  [var106 addObject:var107];
  NSMutableArray *var114 = [NSMutableArray arrayWithCapacity:6];
  NSNumber *var115 = [NSNumber numberWithBool:NO];
  [var114 addObject:var115];
  NSNumber *var116 = [NSNumber numberWithBool:NO];
  [var114 addObject:var116];
  NSNumber *var117 = [NSNumber numberWithBool:NO];
  [var114 addObject:var117];
  NSNumber *var118 = [NSNumber numberWithBool:YES];
  [var114 addObject:var118];
  NSNumber *var119 = [NSNumber numberWithBool:YES];
  [var114 addObject:var119];
  NSNumber *var120 = [NSNumber numberWithBool:YES];
  [var114 addObject:var120];
  [var106 addObject:var114];
  [var0 addObject:var106];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test22 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var1 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var2 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var3 = [NSNumber numberWithBool:NO];
  [var2 addObject:var3];
  NSNumber *var4 = [NSNumber numberWithBool:YES];
  [var2 addObject:var4];
  NSNumber *var5 = [NSNumber numberWithBool:YES];
  [var2 addObject:var5];
  NSNumber *var6 = [NSNumber numberWithBool:YES];
  [var2 addObject:var6];
  [var1 addObject:var2];
  NSMutableArray *var7 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var8 = [NSNumber numberWithBool:NO];
  [var7 addObject:var8];
  NSNumber *var9 = [NSNumber numberWithBool:NO];
  [var7 addObject:var9];
  NSNumber *var10 = [NSNumber numberWithBool:YES];
  [var7 addObject:var10];
  NSNumber *var11 = [NSNumber numberWithBool:YES];
  [var7 addObject:var11];
  [var1 addObject:var7];
  NSMutableArray *var12 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var13 = [NSNumber numberWithBool:NO];
  [var12 addObject:var13];
  NSNumber *var14 = [NSNumber numberWithBool:NO];
  [var12 addObject:var14];
  NSNumber *var15 = [NSNumber numberWithBool:NO];
  [var12 addObject:var15];
  NSNumber *var16 = [NSNumber numberWithBool:YES];
  [var12 addObject:var16];
  [var1 addObject:var12];
  NSMutableArray *var17 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var18 = [NSNumber numberWithBool:NO];
  [var17 addObject:var18];
  NSNumber *var19 = [NSNumber numberWithBool:NO];
  [var17 addObject:var19];
  NSNumber *var20 = [NSNumber numberWithBool:NO];
  [var17 addObject:var20];
  NSNumber *var21 = [NSNumber numberWithBool:NO];
  [var17 addObject:var21];
  [var1 addObject:var17];
  [var0 addObject:var1];
  NSMutableArray *var22 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var23 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var24 = [NSNumber numberWithBool:NO];
  [var23 addObject:var24];
  NSNumber *var25 = [NSNumber numberWithBool:NO];
  [var23 addObject:var25];
  NSNumber *var26 = [NSNumber numberWithBool:NO];
  [var23 addObject:var26];
  NSNumber *var27 = [NSNumber numberWithBool:NO];
  [var23 addObject:var27];
  [var22 addObject:var23];
  NSMutableArray *var28 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var29 = [NSNumber numberWithBool:NO];
  [var28 addObject:var29];
  NSNumber *var30 = [NSNumber numberWithBool:NO];
  [var28 addObject:var30];
  NSNumber *var31 = [NSNumber numberWithBool:YES];
  [var28 addObject:var31];
  NSNumber *var32 = [NSNumber numberWithBool:YES];
  [var28 addObject:var32];
  [var22 addObject:var28];
  NSMutableArray *var33 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var34 = [NSNumber numberWithBool:NO];
  [var33 addObject:var34];
  NSNumber *var35 = [NSNumber numberWithBool:NO];
  [var33 addObject:var35];
  NSNumber *var36 = [NSNumber numberWithBool:NO];
  [var33 addObject:var36];
  NSNumber *var37 = [NSNumber numberWithBool:YES];
  [var33 addObject:var37];
  [var22 addObject:var33];
  NSMutableArray *var38 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var39 = [NSNumber numberWithBool:NO];
  [var38 addObject:var39];
  NSNumber *var40 = [NSNumber numberWithBool:NO];
  [var38 addObject:var40];
  NSNumber *var41 = [NSNumber numberWithBool:NO];
  [var38 addObject:var41];
  NSNumber *var42 = [NSNumber numberWithBool:NO];
  [var38 addObject:var42];
  [var22 addObject:var38];
  [var0 addObject:var22];
  NSMutableArray *var43 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var44 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var45 = [NSNumber numberWithBool:NO];
  [var44 addObject:var45];
  NSNumber *var46 = [NSNumber numberWithBool:NO];
  [var44 addObject:var46];
  NSNumber *var47 = [NSNumber numberWithBool:NO];
  [var44 addObject:var47];
  NSNumber *var48 = [NSNumber numberWithBool:NO];
  [var44 addObject:var48];
  [var43 addObject:var44];
  NSMutableArray *var49 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var50 = [NSNumber numberWithBool:NO];
  [var49 addObject:var50];
  NSNumber *var51 = [NSNumber numberWithBool:NO];
  [var49 addObject:var51];
  NSNumber *var52 = [NSNumber numberWithBool:NO];
  [var49 addObject:var52];
  NSNumber *var53 = [NSNumber numberWithBool:NO];
  [var49 addObject:var53];
  [var43 addObject:var49];
  NSMutableArray *var54 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var55 = [NSNumber numberWithBool:NO];
  [var54 addObject:var55];
  NSNumber *var56 = [NSNumber numberWithBool:NO];
  [var54 addObject:var56];
  NSNumber *var57 = [NSNumber numberWithBool:NO];
  [var54 addObject:var57];
  NSNumber *var58 = [NSNumber numberWithBool:YES];
  [var54 addObject:var58];
  [var43 addObject:var54];
  NSMutableArray *var59 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var60 = [NSNumber numberWithBool:NO];
  [var59 addObject:var60];
  NSNumber *var61 = [NSNumber numberWithBool:NO];
  [var59 addObject:var61];
  NSNumber *var62 = [NSNumber numberWithBool:NO];
  [var59 addObject:var62];
  NSNumber *var63 = [NSNumber numberWithBool:NO];
  [var59 addObject:var63];
  [var43 addObject:var59];
  [var0 addObject:var43];
  NSMutableArray *var64 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var65 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var66 = [NSNumber numberWithBool:NO];
  [var65 addObject:var66];
  NSNumber *var67 = [NSNumber numberWithBool:NO];
  [var65 addObject:var67];
  NSNumber *var68 = [NSNumber numberWithBool:NO];
  [var65 addObject:var68];
  NSNumber *var69 = [NSNumber numberWithBool:NO];
  [var65 addObject:var69];
  [var64 addObject:var65];
  NSMutableArray *var70 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var71 = [NSNumber numberWithBool:NO];
  [var70 addObject:var71];
  NSNumber *var72 = [NSNumber numberWithBool:NO];
  [var70 addObject:var72];
  NSNumber *var73 = [NSNumber numberWithBool:NO];
  [var70 addObject:var73];
  NSNumber *var74 = [NSNumber numberWithBool:NO];
  [var70 addObject:var74];
  [var64 addObject:var70];
  NSMutableArray *var75 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var76 = [NSNumber numberWithBool:NO];
  [var75 addObject:var76];
  NSNumber *var77 = [NSNumber numberWithBool:NO];
  [var75 addObject:var77];
  NSNumber *var78 = [NSNumber numberWithBool:NO];
  [var75 addObject:var78];
  NSNumber *var79 = [NSNumber numberWithBool:NO];
  [var75 addObject:var79];
  [var64 addObject:var75];
  NSMutableArray *var80 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var81 = [NSNumber numberWithBool:NO];
  [var80 addObject:var81];
  NSNumber *var82 = [NSNumber numberWithBool:NO];
  [var80 addObject:var82];
  NSNumber *var83 = [NSNumber numberWithBool:NO];
  [var80 addObject:var83];
  NSNumber *var84 = [NSNumber numberWithBool:NO];
  [var80 addObject:var84];
  [var64 addObject:var80];
  [var0 addObject:var64];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test23 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var1 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var2 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var3 = [NSNumber numberWithBool:NO];
  [var2 addObject:var3];
  NSNumber *var4 = [NSNumber numberWithBool:NO];
  [var2 addObject:var4];
  NSNumber *var5 = [NSNumber numberWithBool:NO];
  [var2 addObject:var5];
  NSNumber *var6 = [NSNumber numberWithBool:NO];
  [var2 addObject:var6];
  [var1 addObject:var2];
  NSMutableArray *var7 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var8 = [NSNumber numberWithBool:NO];
  [var7 addObject:var8];
  NSNumber *var9 = [NSNumber numberWithBool:NO];
  [var7 addObject:var9];
  NSNumber *var10 = [NSNumber numberWithBool:YES];
  [var7 addObject:var10];
  NSNumber *var11 = [NSNumber numberWithBool:YES];
  [var7 addObject:var11];
  [var1 addObject:var7];
  NSMutableArray *var12 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var13 = [NSNumber numberWithBool:NO];
  [var12 addObject:var13];
  NSNumber *var14 = [NSNumber numberWithBool:NO];
  [var12 addObject:var14];
  NSNumber *var15 = [NSNumber numberWithBool:NO];
  [var12 addObject:var15];
  NSNumber *var16 = [NSNumber numberWithBool:YES];
  [var12 addObject:var16];
  [var1 addObject:var12];
  NSMutableArray *var17 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var18 = [NSNumber numberWithBool:NO];
  [var17 addObject:var18];
  NSNumber *var19 = [NSNumber numberWithBool:NO];
  [var17 addObject:var19];
  NSNumber *var20 = [NSNumber numberWithBool:NO];
  [var17 addObject:var20];
  NSNumber *var21 = [NSNumber numberWithBool:NO];
  [var17 addObject:var21];
  [var1 addObject:var17];
  [var0 addObject:var1];
  NSMutableArray *var22 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var23 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var24 = [NSNumber numberWithBool:NO];
  [var23 addObject:var24];
  NSNumber *var25 = [NSNumber numberWithBool:NO];
  [var23 addObject:var25];
  NSNumber *var26 = [NSNumber numberWithBool:NO];
  [var23 addObject:var26];
  NSNumber *var27 = [NSNumber numberWithBool:NO];
  [var23 addObject:var27];
  [var22 addObject:var23];
  NSMutableArray *var28 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var29 = [NSNumber numberWithBool:NO];
  [var28 addObject:var29];
  NSNumber *var30 = [NSNumber numberWithBool:NO];
  [var28 addObject:var30];
  NSNumber *var31 = [NSNumber numberWithBool:NO];
  [var28 addObject:var31];
  NSNumber *var32 = [NSNumber numberWithBool:NO];
  [var28 addObject:var32];
  [var22 addObject:var28];
  NSMutableArray *var33 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var34 = [NSNumber numberWithBool:NO];
  [var33 addObject:var34];
  NSNumber *var35 = [NSNumber numberWithBool:NO];
  [var33 addObject:var35];
  NSNumber *var36 = [NSNumber numberWithBool:NO];
  [var33 addObject:var36];
  NSNumber *var37 = [NSNumber numberWithBool:YES];
  [var33 addObject:var37];
  [var22 addObject:var33];
  NSMutableArray *var38 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var39 = [NSNumber numberWithBool:NO];
  [var38 addObject:var39];
  NSNumber *var40 = [NSNumber numberWithBool:NO];
  [var38 addObject:var40];
  NSNumber *var41 = [NSNumber numberWithBool:NO];
  [var38 addObject:var41];
  NSNumber *var42 = [NSNumber numberWithBool:NO];
  [var38 addObject:var42];
  [var22 addObject:var38];
  [var0 addObject:var22];
  NSMutableArray *var43 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var44 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var45 = [NSNumber numberWithBool:NO];
  [var44 addObject:var45];
  NSNumber *var46 = [NSNumber numberWithBool:NO];
  [var44 addObject:var46];
  NSNumber *var47 = [NSNumber numberWithBool:NO];
  [var44 addObject:var47];
  NSNumber *var48 = [NSNumber numberWithBool:NO];
  [var44 addObject:var48];
  [var43 addObject:var44];
  NSMutableArray *var49 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var50 = [NSNumber numberWithBool:NO];
  [var49 addObject:var50];
  NSNumber *var51 = [NSNumber numberWithBool:NO];
  [var49 addObject:var51];
  NSNumber *var52 = [NSNumber numberWithBool:NO];
  [var49 addObject:var52];
  NSNumber *var53 = [NSNumber numberWithBool:NO];
  [var49 addObject:var53];
  [var43 addObject:var49];
  NSMutableArray *var54 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var55 = [NSNumber numberWithBool:NO];
  [var54 addObject:var55];
  NSNumber *var56 = [NSNumber numberWithBool:NO];
  [var54 addObject:var56];
  NSNumber *var57 = [NSNumber numberWithBool:NO];
  [var54 addObject:var57];
  NSNumber *var58 = [NSNumber numberWithBool:NO];
  [var54 addObject:var58];
  [var43 addObject:var54];
  NSMutableArray *var59 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var60 = [NSNumber numberWithBool:NO];
  [var59 addObject:var60];
  NSNumber *var61 = [NSNumber numberWithBool:NO];
  [var59 addObject:var61];
  NSNumber *var62 = [NSNumber numberWithBool:NO];
  [var59 addObject:var62];
  NSNumber *var63 = [NSNumber numberWithBool:NO];
  [var59 addObject:var63];
  [var43 addObject:var59];
  [var0 addObject:var43];
  NSMutableArray *var64 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var65 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var66 = [NSNumber numberWithBool:NO];
  [var65 addObject:var66];
  NSNumber *var67 = [NSNumber numberWithBool:NO];
  [var65 addObject:var67];
  NSNumber *var68 = [NSNumber numberWithBool:NO];
  [var65 addObject:var68];
  NSNumber *var69 = [NSNumber numberWithBool:NO];
  [var65 addObject:var69];
  [var64 addObject:var65];
  NSMutableArray *var70 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var71 = [NSNumber numberWithBool:NO];
  [var70 addObject:var71];
  NSNumber *var72 = [NSNumber numberWithBool:NO];
  [var70 addObject:var72];
  NSNumber *var73 = [NSNumber numberWithBool:NO];
  [var70 addObject:var73];
  NSNumber *var74 = [NSNumber numberWithBool:NO];
  [var70 addObject:var74];
  [var64 addObject:var70];
  NSMutableArray *var75 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var76 = [NSNumber numberWithBool:NO];
  [var75 addObject:var76];
  NSNumber *var77 = [NSNumber numberWithBool:NO];
  [var75 addObject:var77];
  NSNumber *var78 = [NSNumber numberWithBool:NO];
  [var75 addObject:var78];
  NSNumber *var79 = [NSNumber numberWithBool:NO];
  [var75 addObject:var79];
  [var64 addObject:var75];
  NSMutableArray *var80 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var81 = [NSNumber numberWithBool:NO];
  [var80 addObject:var81];
  NSNumber *var82 = [NSNumber numberWithBool:NO];
  [var80 addObject:var82];
  NSNumber *var83 = [NSNumber numberWithBool:NO];
  [var80 addObject:var83];
  NSNumber *var84 = [NSNumber numberWithBool:NO];
  [var80 addObject:var84];
  [var64 addObject:var80];
  [var0 addObject:var64];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test24 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var1 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var2 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var3 = [NSNumber numberWithBool:YES];
  [var2 addObject:var3];
  NSNumber *var4 = [NSNumber numberWithBool:YES];
  [var2 addObject:var4];
  NSNumber *var5 = [NSNumber numberWithBool:YES];
  [var2 addObject:var5];
  NSNumber *var6 = [NSNumber numberWithBool:YES];
  [var2 addObject:var6];
  [var1 addObject:var2];
  NSMutableArray *var7 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var8 = [NSNumber numberWithBool:NO];
  [var7 addObject:var8];
  NSNumber *var9 = [NSNumber numberWithBool:YES];
  [var7 addObject:var9];
  NSNumber *var10 = [NSNumber numberWithBool:YES];
  [var7 addObject:var10];
  NSNumber *var11 = [NSNumber numberWithBool:YES];
  [var7 addObject:var11];
  [var1 addObject:var7];
  NSMutableArray *var12 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var13 = [NSNumber numberWithBool:NO];
  [var12 addObject:var13];
  NSNumber *var14 = [NSNumber numberWithBool:NO];
  [var12 addObject:var14];
  NSNumber *var15 = [NSNumber numberWithBool:YES];
  [var12 addObject:var15];
  NSNumber *var16 = [NSNumber numberWithBool:YES];
  [var12 addObject:var16];
  [var1 addObject:var12];
  NSMutableArray *var17 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var18 = [NSNumber numberWithBool:NO];
  [var17 addObject:var18];
  NSNumber *var19 = [NSNumber numberWithBool:NO];
  [var17 addObject:var19];
  NSNumber *var20 = [NSNumber numberWithBool:NO];
  [var17 addObject:var20];
  NSNumber *var21 = [NSNumber numberWithBool:YES];
  [var17 addObject:var21];
  [var1 addObject:var17];
  [var0 addObject:var1];
  NSMutableArray *var22 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var23 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var24 = [NSNumber numberWithBool:NO];
  [var23 addObject:var24];
  NSNumber *var25 = [NSNumber numberWithBool:NO];
  [var23 addObject:var25];
  NSNumber *var26 = [NSNumber numberWithBool:NO];
  [var23 addObject:var26];
  NSNumber *var27 = [NSNumber numberWithBool:NO];
  [var23 addObject:var27];
  [var22 addObject:var23];
  NSMutableArray *var28 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var29 = [NSNumber numberWithBool:NO];
  [var28 addObject:var29];
  NSNumber *var30 = [NSNumber numberWithBool:YES];
  [var28 addObject:var30];
  NSNumber *var31 = [NSNumber numberWithBool:YES];
  [var28 addObject:var31];
  NSNumber *var32 = [NSNumber numberWithBool:YES];
  [var28 addObject:var32];
  [var22 addObject:var28];
  NSMutableArray *var33 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var34 = [NSNumber numberWithBool:NO];
  [var33 addObject:var34];
  NSNumber *var35 = [NSNumber numberWithBool:NO];
  [var33 addObject:var35];
  NSNumber *var36 = [NSNumber numberWithBool:YES];
  [var33 addObject:var36];
  NSNumber *var37 = [NSNumber numberWithBool:YES];
  [var33 addObject:var37];
  [var22 addObject:var33];
  NSMutableArray *var38 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var39 = [NSNumber numberWithBool:NO];
  [var38 addObject:var39];
  NSNumber *var40 = [NSNumber numberWithBool:NO];
  [var38 addObject:var40];
  NSNumber *var41 = [NSNumber numberWithBool:NO];
  [var38 addObject:var41];
  NSNumber *var42 = [NSNumber numberWithBool:YES];
  [var38 addObject:var42];
  [var22 addObject:var38];
  [var0 addObject:var22];
  NSMutableArray *var43 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var44 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var45 = [NSNumber numberWithBool:NO];
  [var44 addObject:var45];
  NSNumber *var46 = [NSNumber numberWithBool:NO];
  [var44 addObject:var46];
  NSNumber *var47 = [NSNumber numberWithBool:NO];
  [var44 addObject:var47];
  NSNumber *var48 = [NSNumber numberWithBool:NO];
  [var44 addObject:var48];
  [var43 addObject:var44];
  NSMutableArray *var49 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var50 = [NSNumber numberWithBool:NO];
  [var49 addObject:var50];
  NSNumber *var51 = [NSNumber numberWithBool:NO];
  [var49 addObject:var51];
  NSNumber *var52 = [NSNumber numberWithBool:NO];
  [var49 addObject:var52];
  NSNumber *var53 = [NSNumber numberWithBool:NO];
  [var49 addObject:var53];
  [var43 addObject:var49];
  NSMutableArray *var54 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var55 = [NSNumber numberWithBool:NO];
  [var54 addObject:var55];
  NSNumber *var56 = [NSNumber numberWithBool:NO];
  [var54 addObject:var56];
  NSNumber *var57 = [NSNumber numberWithBool:YES];
  [var54 addObject:var57];
  NSNumber *var58 = [NSNumber numberWithBool:YES];
  [var54 addObject:var58];
  [var43 addObject:var54];
  NSMutableArray *var59 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var60 = [NSNumber numberWithBool:NO];
  [var59 addObject:var60];
  NSNumber *var61 = [NSNumber numberWithBool:NO];
  [var59 addObject:var61];
  NSNumber *var62 = [NSNumber numberWithBool:NO];
  [var59 addObject:var62];
  NSNumber *var63 = [NSNumber numberWithBool:YES];
  [var59 addObject:var63];
  [var43 addObject:var59];
  [var0 addObject:var43];
  NSMutableArray *var64 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var65 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var66 = [NSNumber numberWithBool:NO];
  [var65 addObject:var66];
  NSNumber *var67 = [NSNumber numberWithBool:NO];
  [var65 addObject:var67];
  NSNumber *var68 = [NSNumber numberWithBool:NO];
  [var65 addObject:var68];
  NSNumber *var69 = [NSNumber numberWithBool:NO];
  [var65 addObject:var69];
  [var64 addObject:var65];
  NSMutableArray *var70 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var71 = [NSNumber numberWithBool:NO];
  [var70 addObject:var71];
  NSNumber *var72 = [NSNumber numberWithBool:NO];
  [var70 addObject:var72];
  NSNumber *var73 = [NSNumber numberWithBool:NO];
  [var70 addObject:var73];
  NSNumber *var74 = [NSNumber numberWithBool:NO];
  [var70 addObject:var74];
  [var64 addObject:var70];
  NSMutableArray *var75 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var76 = [NSNumber numberWithBool:NO];
  [var75 addObject:var76];
  NSNumber *var77 = [NSNumber numberWithBool:NO];
  [var75 addObject:var77];
  NSNumber *var78 = [NSNumber numberWithBool:NO];
  [var75 addObject:var78];
  NSNumber *var79 = [NSNumber numberWithBool:NO];
  [var75 addObject:var79];
  [var64 addObject:var75];
  NSMutableArray *var80 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var81 = [NSNumber numberWithBool:NO];
  [var80 addObject:var81];
  NSNumber *var82 = [NSNumber numberWithBool:NO];
  [var80 addObject:var82];
  NSNumber *var83 = [NSNumber numberWithBool:NO];
  [var80 addObject:var83];
  NSNumber *var84 = [NSNumber numberWithBool:YES];
  [var80 addObject:var84];
  [var64 addObject:var80];
  [var0 addObject:var64];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test25 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableArray *var0 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var1 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var2 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var3 = [NSNumber numberWithBool:NO];
  [var2 addObject:var3];
  NSNumber *var4 = [NSNumber numberWithBool:NO];
  [var2 addObject:var4];
  NSNumber *var5 = [NSNumber numberWithBool:NO];
  [var2 addObject:var5];
  NSNumber *var6 = [NSNumber numberWithBool:NO];
  [var2 addObject:var6];
  [var1 addObject:var2];
  NSMutableArray *var7 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var8 = [NSNumber numberWithBool:NO];
  [var7 addObject:var8];
  NSNumber *var9 = [NSNumber numberWithBool:YES];
  [var7 addObject:var9];
  NSNumber *var10 = [NSNumber numberWithBool:YES];
  [var7 addObject:var10];
  NSNumber *var11 = [NSNumber numberWithBool:YES];
  [var7 addObject:var11];
  [var1 addObject:var7];
  NSMutableArray *var12 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var13 = [NSNumber numberWithBool:NO];
  [var12 addObject:var13];
  NSNumber *var14 = [NSNumber numberWithBool:NO];
  [var12 addObject:var14];
  NSNumber *var15 = [NSNumber numberWithBool:YES];
  [var12 addObject:var15];
  NSNumber *var16 = [NSNumber numberWithBool:YES];
  [var12 addObject:var16];
  [var1 addObject:var12];
  NSMutableArray *var17 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var18 = [NSNumber numberWithBool:NO];
  [var17 addObject:var18];
  NSNumber *var19 = [NSNumber numberWithBool:NO];
  [var17 addObject:var19];
  NSNumber *var20 = [NSNumber numberWithBool:NO];
  [var17 addObject:var20];
  NSNumber *var21 = [NSNumber numberWithBool:YES];
  [var17 addObject:var21];
  [var1 addObject:var17];
  [var0 addObject:var1];
  NSMutableArray *var22 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var23 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var24 = [NSNumber numberWithBool:NO];
  [var23 addObject:var24];
  NSNumber *var25 = [NSNumber numberWithBool:NO];
  [var23 addObject:var25];
  NSNumber *var26 = [NSNumber numberWithBool:NO];
  [var23 addObject:var26];
  NSNumber *var27 = [NSNumber numberWithBool:NO];
  [var23 addObject:var27];
  [var22 addObject:var23];
  NSMutableArray *var28 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var29 = [NSNumber numberWithBool:NO];
  [var28 addObject:var29];
  NSNumber *var30 = [NSNumber numberWithBool:NO];
  [var28 addObject:var30];
  NSNumber *var31 = [NSNumber numberWithBool:NO];
  [var28 addObject:var31];
  NSNumber *var32 = [NSNumber numberWithBool:NO];
  [var28 addObject:var32];
  [var22 addObject:var28];
  NSMutableArray *var33 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var34 = [NSNumber numberWithBool:NO];
  [var33 addObject:var34];
  NSNumber *var35 = [NSNumber numberWithBool:NO];
  [var33 addObject:var35];
  NSNumber *var36 = [NSNumber numberWithBool:YES];
  [var33 addObject:var36];
  NSNumber *var37 = [NSNumber numberWithBool:YES];
  [var33 addObject:var37];
  [var22 addObject:var33];
  NSMutableArray *var38 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var39 = [NSNumber numberWithBool:NO];
  [var38 addObject:var39];
  NSNumber *var40 = [NSNumber numberWithBool:NO];
  [var38 addObject:var40];
  NSNumber *var41 = [NSNumber numberWithBool:NO];
  [var38 addObject:var41];
  NSNumber *var42 = [NSNumber numberWithBool:YES];
  [var38 addObject:var42];
  [var22 addObject:var38];
  [var0 addObject:var22];
  NSMutableArray *var43 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var44 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var45 = [NSNumber numberWithBool:NO];
  [var44 addObject:var45];
  NSNumber *var46 = [NSNumber numberWithBool:NO];
  [var44 addObject:var46];
  NSNumber *var47 = [NSNumber numberWithBool:NO];
  [var44 addObject:var47];
  NSNumber *var48 = [NSNumber numberWithBool:NO];
  [var44 addObject:var48];
  [var43 addObject:var44];
  NSMutableArray *var49 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var50 = [NSNumber numberWithBool:NO];
  [var49 addObject:var50];
  NSNumber *var51 = [NSNumber numberWithBool:NO];
  [var49 addObject:var51];
  NSNumber *var52 = [NSNumber numberWithBool:NO];
  [var49 addObject:var52];
  NSNumber *var53 = [NSNumber numberWithBool:NO];
  [var49 addObject:var53];
  [var43 addObject:var49];
  NSMutableArray *var54 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var55 = [NSNumber numberWithBool:NO];
  [var54 addObject:var55];
  NSNumber *var56 = [NSNumber numberWithBool:NO];
  [var54 addObject:var56];
  NSNumber *var57 = [NSNumber numberWithBool:NO];
  [var54 addObject:var57];
  NSNumber *var58 = [NSNumber numberWithBool:NO];
  [var54 addObject:var58];
  [var43 addObject:var54];
  NSMutableArray *var59 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var60 = [NSNumber numberWithBool:NO];
  [var59 addObject:var60];
  NSNumber *var61 = [NSNumber numberWithBool:NO];
  [var59 addObject:var61];
  NSNumber *var62 = [NSNumber numberWithBool:NO];
  [var59 addObject:var62];
  NSNumber *var63 = [NSNumber numberWithBool:YES];
  [var59 addObject:var63];
  [var43 addObject:var59];
  [var0 addObject:var43];
  NSMutableArray *var64 = [NSMutableArray arrayWithCapacity:4];
  NSMutableArray *var65 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var66 = [NSNumber numberWithBool:NO];
  [var65 addObject:var66];
  NSNumber *var67 = [NSNumber numberWithBool:NO];
  [var65 addObject:var67];
  NSNumber *var68 = [NSNumber numberWithBool:NO];
  [var65 addObject:var68];
  NSNumber *var69 = [NSNumber numberWithBool:NO];
  [var65 addObject:var69];
  [var64 addObject:var65];
  NSMutableArray *var70 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var71 = [NSNumber numberWithBool:NO];
  [var70 addObject:var71];
  NSNumber *var72 = [NSNumber numberWithBool:NO];
  [var70 addObject:var72];
  NSNumber *var73 = [NSNumber numberWithBool:NO];
  [var70 addObject:var73];
  NSNumber *var74 = [NSNumber numberWithBool:NO];
  [var70 addObject:var74];
  [var64 addObject:var70];
  NSMutableArray *var75 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var76 = [NSNumber numberWithBool:NO];
  [var75 addObject:var76];
  NSNumber *var77 = [NSNumber numberWithBool:NO];
  [var75 addObject:var77];
  NSNumber *var78 = [NSNumber numberWithBool:NO];
  [var75 addObject:var78];
  NSNumber *var79 = [NSNumber numberWithBool:NO];
  [var75 addObject:var79];
  [var64 addObject:var75];
  NSMutableArray *var80 = [NSMutableArray arrayWithCapacity:4];
  NSNumber *var81 = [NSNumber numberWithBool:NO];
  [var80 addObject:var81];
  NSNumber *var82 = [NSNumber numberWithBool:NO];
  [var80 addObject:var82];
  NSNumber *var83 = [NSNumber numberWithBool:NO];
  [var80 addObject:var83];
  NSNumber *var84 = [NSNumber numberWithBool:NO];
  [var80 addObject:var84];
  [var64 addObject:var80];
  [var0 addObject:var64];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test26 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableDictionary *var0 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var1 = @"func";
  NSString *var2 = @"rts";
  [var0 setObject:var2 forKey:var1];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test27 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSMutableDictionary *var0 = [NSMutableDictionary dictionaryWithCapacity:1];
  NSString *var1 = @"func";
  NSString *var2 = @"rt1";
  [var0 setObject:var2 forKey:var1];
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test28 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSString *var0 = @"2012-08-01T00:00:00+00:00";
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

- (void)test29 {
  ReQLConnection *connection = [ReQLConnection new];
  XCTAssert([connection isOpen]);
  NSString *var0 = @"2012-08-01T00:00:00+00:00";
  XCTAssert([var0 isEqualTo:var0]);
  [connection close];
}

@end
